export const FormActionTypes = {
  FORM_SET_NUMBER_OF_INPUT_FIELDS: 'FORM_SET_NUMBER_OF_INPUT_FIELDS',
  FORM_TOGGLE_SHOW_MEMOIZED_COMPONENTS: 'FORM_TOGGLE_SHOW_MEMOIZED_COMPONENTS',
  FORM_ON_CHANGE: 'FORM_ON_CHANGE'
};
