export const SET_IN_DROP_ZONE = 'SET_IN_DROP_ZONE';
export const ADD_VALIDATED_FILE_LIST = 'ADD_VALIDATED_FILE_LIST';
export const DELETE_FILE_FROM_LIST = 'DELETE_FILE_FROM_LIST';
export const SET_ERROR = 'SET_ERROR';
